[AyyoOS]
name=AyyoOS
version=0.1
codename=Ayyo
tagline=Your PC Has a Personality

[Personality]
default_mode=funny
default_language=telugu

[Modes]
normal=true
chill=true
funny=true
savage=true

[Branding]
logo_name=AyyoOS
desktop_name=Ayyo Desktop
engine_name=AyyoEngine
monitor_name=AyyoMonitor
notification_name=AyyoNotify
